<html>
<head>
<link href="css/terms.css" rel="stylesheet" type="text/css"/>
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200' rel='stylesheet' type='text/css'>

</head>
<body>
</body>

<div class='wrapper'>

<div class='termswrapper'>
	<div class='termsbody'>
		<div class='termsheader'>
			<div class='termslogo'><a class="termslogolink" href="index.php">Clofus</div>
			<div class='termsmenu'>Home&nbsp;&nbsp;&nbsp;How it works!&nbsp;&nbsp;&nbsp;Invite friend</div>
		</div>
		
		<div class='termsfeed'>
		<div class="titletext">Terms & Conditions</div>
		<div class="termsfeedtext">
		<p>
			1. ABOUT US. We are Clofus, Inc. ( Clofus ,  us ,  we  or  our ), a corporation registered under the laws of the state of Delaware in the United States with our principal office address at 301 Brannan Street, San Francisco, CA 94107.
		</p>
		<p>
2. ABOUT THE Clofus SERVICES. We provide users ( you ,  your ) with services, delivered via the Clofus website (currently located at http://www.Clofus.com), the Clofus toolbar, the Clofus mobile applications and/or any other platform or media through which we make such services available from time to time, that allow you to explore the Internet, find new websites that may be of interest to you, receive recommendations of websites from Clofus, and join a community of individuals with similar tastes and interests (collectively, the  Services ).
</p>
<p>
3. ABOUT THESE TERMS OF SERVICE. These Clofus Terms of Service ( Terms of Service ) set forth the legally binding terms for your use of the Services. You should also read Clofus s Privacy Policy, currently located at http://www.Clofus.com/privacy/, which contains important information about how we use your data. By accessing and using the Services, you agree to comply with and be bound by these Terms of Service, whether you are a  Member  (meaning that you have registered and created an account with Clofus or through one of Clofus s connected social networking communities ( Partner Communities ), and have created a  Clofus Profile ), or you are a  Visitor  (meaning you are simply browsing the Clofus website or viewing content from or affiliated with Clofus). The term  User  refers to a Member or a Visitor, as applicable. If you do not agree to these Terms of Service, you may not access or use the Services.
</p>
<p>
4. CHANGES TO THESE TERMS OF SERVICE. Clofus reserves the right to change these Terms of Service from time to time. We will usually inform you of any changes by posting the updated Terms of Service on the Clofus website. If we make any material changes to these Terms of Service, we will post a notification on the Clofus website and, if you are a Member, notify you via email and/or by asking you to review the changes to these Terms of Service the next time you login to access the Services. Your continued use of the Services after the time the changes are communicated as set out in this section will indicate your acceptance of the Terms of Service, including those changes.
</p>
<p>
5. OTHER TERMS THAT MAY APPLY. If you sign up for additional services from Clofus, those additional services may be governed by terms associated with those services, which will apply to you in addition to these Terms of Service. If there is a conflict between these Terms of Service and terms and conditions for such additional services, the latter shall take precedence with respect to the additional services.
</p><p>
6. THE BASIS ON WHICH WE MAKE THE SERVICES AVAILABLE TO YOU. Clofus reserves the right, at its sole discretion, to modify, discontinue, or terminate the Services at any time and without prior notice. Clofus may restrict, deactivate or terminate your access to the Services or your Clofus Profile for any reason.
</p><p>
7. YOUR Clofus ACCOUNT & PROFILE
</p><p>
a. ELIGIBILITY. By using the Services, whether as a Member or as a Visitor, you represent and warrant that: (a) all required registration information you submit either as part of the Clofus registration process or by your registration through a Partner Community is truthful and accurate; (b) you will maintain the accuracy of such information; (c) you are thirteen (13) years of age or older; and (d) your use of the Services does not violate any applicable law or regulation. Your Clofus Profile may be deleted without warning if we have reason to believe that you do not meet these eligibility requirements. Parental control protections for computers and mobile devices are commercially available that may assist you in limiting access to material that is harmful to minors. Information about protecting children online is available at:
http://onguardonline.gov/topics/protect-kids-online.
</p><p>
b. YOUR PASSWORD. When you sign up to become a Clofus Member, you will be asked to choose a username and a password for your Clofus Profile, or Clofus may assign a password to you that you may change. You are entirely responsible for maintaining the confidentiality of your password and all use of your Clofus Profile. You agree not to use the Clofus Profile, username, or password of another Member. You agree to notify us immediately if you suspect any unauthorized use of your Clofus Profile or access to your password.
</p><p>
c. RESTRICTIONS. You may not have more than one Clofus Profile unless expressly authorized in writing by Clofus. Multiple Clofus accounts held by the same individual may be subject to deletion by Clofus. Accounts may not be created or used with the primary intention to promote a product or service unless expressly authorized in writing by Clofus, and any such accounts may be subject to deletion by Clofus.
</p><p>
d. TERM. These Terms of Service shall remain in full force and effect while you use the Services. You may delete your Clofus Profile and end your account at any time, for any reason by following the instructions at the Clofus Help Center, http://help.Clofus.com/customer/portal/articles/665202-account-settings. We may restrict, deactivate or terminate your account for any reason.
</p><p>
e. EFFECTS OF TERMINATION. You understand that termination of these Terms of Service and your Clofus Profile may involve deletion of your Clofus Profile information from our live databases without the ability to reactivate or restore features of the account, but that our servers may maintain such information for archival or legal purposes. We will not have any liability whatsoever to you for any restriction or termination of your Clofus Profile or related deletion (or retention, as stated above) of your information.
</p><p>
f. PERMITTED USE OF SERVICES. The Services are made available to you for your non-commercial use only. You may not use Clofus to promote a product or service and Clofus makes no guarantee of traffic to any particular website. You may not modify, reproduce, distribute, publish, license, create derivative works from or sell any information or software associated with the Services. Furthermore, you may not use the Services in any manner that could damage, disable, overburden, or impair the Services, or that could interfere with any other party s use and enjoyment of the Services. You may not use any third-party APIs, software, tools or scripts to access the website or the underlying technology, unless expressly authorized in writing by Clofus, or as permitted in any other agreement you enter into with Clofus.
</p><p>
8. INTELLECTUAL PROPERTY OWNERSHIP. You acknowledge that Clofus owns all right, title and interest in and to the Services, including without limitation, all underlying software and technology and all Intellectual Property Rights in relation to the Services, other than as described in Sections 10(b) and (c) of these Terms of Service.  Intellectual Property Rights  means any and all intellectual property rights existing from time to time in any part of the world under applicable law, including without limitation applicable patent law, copyright law, trade secret law, trademark law, unfair competition law, and any and all applications, renewals, extensions and restorations of such rights, now or hereafter in effect worldwide. Clofus grants you the personal, non-exclusive, revocable, non-transferable right to use the software and technology that is provided to you as part of the Services for the sole purpose of your use of the Services to the extent permitted under these Terms of Service.
</p><p>
9. COPYRIGHT POLICY. Clofus respects the Intellectual Property Rights of creators. If you believe that your work has been copied, posted or included within the Services in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: (i) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (ii) a description of the copyrighted work that you claim has been infringed; (iii) a description of where the material that you claim is infringing is located on the Services; (iv) your address, telephone number, and e-mail address; (v) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; (vi) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner s behalf. Contact information for our Copyright Agent for notice of claims of copyright infringement is as follows:
Clofus, Inc.
http://www.clofus.com
</p><p>
We reserve the right to remove Content alleged to be infringing in our sole discretion and without notice. It is our policy to terminate membership privileges of any Clofus Member who repeatedly is accused of infringing copyrights.
</p><p>
10. CONTENT. The Services contain different types of Content: Clofus Content, Third Party Content and User Content.  Content  means any and all postings, e-mails, messages, recommendations, comments, text, files, images, photos, video, sounds, works of authorship, feedback, bug reports, or other materials. Each type of Content that you encounter has different rules and restrictions, as set forth below:
</p><p>
a. Clofus CONTENT AND OWNERSHIP. As between Clofus and you, Clofus owns or controls all right, title and interest in the Services and in the Content that it has placed on and within the Services, including its logos, trademarks and all other Intellectual Property Rights it controls ( Clofus Content ).
</p><p>
b. THIRD-PARTY CONTENT. Content from other Users, advertisers and other third parties may be made available to you through the Services as you interact with and  Stumble  as part of the Services ( Third Party Content ). You may add or recommend such Third Party Content to the Clofus Services and to other Users by using the  I Like It!  feature and you may share Third Party Content with others through e-mail, messaging or through your social network using the share feature. We do not filter or otherwise exercise control over such Third Party Content. Accordingly, you agree that we are not responsible for any such Third Party Content, including advertising and/or information about third-party products or services. We make no guarantees about the accuracy, currency, suitability, quality or legality of the information in such Third Party Content, and we assume no responsibility for unintended, objectionable, inaccurate, misleading or unlawful Third Party Content. By choosing your preferences, you can designate types and categories of Content you prefer to access, but Clofus cannot guarantee that you will only access the types and categories of Content you designate. Clofus is not responsible for Third Party Content that contains or delivers viruses, Trojan horses, worms, time bombs, cancelbots, corrupted files, spyware, malware, or other harmful content or code. Rather, you are responsible for installing, maintaining and using effective anti-virus and spyware prevention technologies.
</p><p>
c. USER CONTENT. We do not claim ownership in any Content that you post on, deliver to, or otherwise make available to the Services, through your Clofus Profile, your comments, or other features of the Services that may allow you to post your own Content ( User Content ). By posting User Content, you hereby grant to us an unrestricted, irrevocable, perpetual, non-exclusive, fully-paid and royalty-free license (with the right to sublicense through unlimited levels of sublicensees) to use, copy, perform, display, create derivative works of, and distribute your User Content in any and all media or distribution method (now known or later developed) throughout the world. The licenses granted under this Section will survive the termination or expiration of these Terms of Service for any reason. You are solely responsible for any and all User Content that you post on the Services and for your interactions with other Users. You should only post User Content to the Services that you own and that you are comfortable sharing with others under the terms and conditions set forth herein. You may not post a photograph or video of another person without that person s permission. Other Users of the Service will be able to view any Content you post to the Services, subject to your limited ability to restrict access to your Content by changing your account preferences and settings. You represent and warrant that: (i) you own the User Content posted by you on the Service or otherwise have the right to grant the licenses set forth in these Terms of Service, and (ii) your User Content and the use of it by Clofus as permitted by the license granted in these Terms of Service does not violate the privacy rights, publicity rights, Intellectual Property Rights, or other rights of any person.
</p><p>
d. CONTENT RESTRICTIONS. Except for that Content that is owned by you, that is in the public domain, for which you have been given written permission, or as expressly permitted under these Terms of Service, you agree not to (i) modify, copy, publish, display, transmit, distribute, perform, sell or create derivative works based on the Content and Services; (ii) rent, lease, loan or sell access to the Services; or (iii) decompile, reverse engineer or copy any Content (other than the Content you post) or the Services. You also agree to not remove, obscure or alter Clofus s copyright notice, logos, trademarks or other proprietary rights notices affixed to or contained within the Services. You will not interfere with, disrupt or create an undue burden on the Services or the networks or services connected to the Services.
</p><p>
e. PROHIBITED CONTENT. You agree that you will not post and that you will not recommend through the Services any Prohibited Content.  Prohibited Content  includes, without limitation, Content that: (i) is offensive or promotes racism, bigotry, hatred or physical harm of any kind; (ii) harasses or advocates harassment of another person; (iii) involves the transmission of  junk mail,   chain letters,  unsolicited mass mailing or  spamming ; (iv) is false, misleading, libelous, defamatory or promotes, endorses or furthers illegal activities; (v) infringes the Intellectual Property Rights of another person; (vi) is involved in the exploitation of persons under the age of eighteen (18) in a sexual or violent manner, or solicits personal information from anyone under thirteen (13); (vii) contains viruses, Trojan horses, worms, time bombs, cancelbots, corrupted files, spyware, malware or other harmful content or code; or (viii) otherwise violates applicable law, the terms of these Terms of Service or potentially creates liability for Clofus. Any accounts posting, hosting or recommending Prohibited Content are subject to termination. We reserve the right to remove Content (including websites) that we determine in our sole discretion is unlawful, fraudulent, threatening, libelous, defamatory, obscene or otherwise objectionable. We also reserve the right to remove Content that we determine in our sole discretion is primarily intended to promote a product or service. We have the right (but not the obligation) to investigate or review any Content (including websites) and delete (or modify) any Content that in our sole judgment violates these Terms of Service or which is Prohibited Content, or may otherwise violate the rights, harm or threaten the safety of any User or any other person, or create potential liability for us or any User.
</p><p>
11. YOUR BREACH OF THESE TERMS OF SERVICE. Any breach by you of these Terms of Service may result in, among other things, termination or suspension of your rights to use the Services and deletion of your Clofus Profile.
</p><p>
12. LEGAL OBLIGATIONS. In order to cooperate with legitimate governmental or regulator requests, subpoenas or court orders, to protect our systems and Users, to protect the property and rights of Clofus or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, illegal, unethical or legally actionable, we may access and disclose any information and Content we consider necessary or appropriate, including, without limitation, Clofus Profile information (i.e. name, e-mail address, etc.), IP address, traffic information, usage history and posted Content.
</p><p>
13. DISCLAIMER OF WARRANTIES. The Services are provided  as is  and on an  as available  basis, with no warranties whatsoever. Clofus expressly disclaims to the fullest extent permitted by law all express, implied, and statutory warranties, including without limitation the warranties of merchantability, fitness for a particular purpose, title, and noninfringement of proprietary rights. Clofus disclaims any warranties regarding the security, reliability, timeliness, availability, quality and performance of the Content and the Services. Clofus disclaims any responsibility for any harm resulting from your viewing of the Content and use of the Services. You understand and agree that you view the Content and use the Services at your own discretion and risk and that you will be solely responsible for any injury to you, damages to your computer system or loss of data that results from your viewing of the Content and use of the Services. Some states or other jurisdictions do not allow the exclusion of implied warranties, so the above exclusions may not apply to you. You may also have other rights that vary from state to state and jurisdiction to jurisdiction.
</p><p>
14. LIMITATION OF LIABILITY. Under no circumstances shall Clofus be liable to any User on account of that User s use or misuse of the Content or the Services. Such limitation of liability shall apply to prevent recovery of indirect, incidental, consequential, special, exemplary, and punitive damages whether such claim is based on warranty, contract, tort (including negligence), or otherwise (even if Clofus has been advised of the possibility of such damages). This limitation of liability shall apply whether the damages arise from use or misuse of and reliance on the Content or Services, from inability to use the Content or Services, or from the interruption, suspension, or termination of the Content or Services (including such damages incurred by third parties). Some states or other jurisdictions do not allow the exclusion or limitation of liability for incidental or consequential damages, so the above limitations and exclusions may not apply to you.
</p><p>
15. RELEASE. You hereby release us, our officers, employees, investors, agents and successors from claims, demands, any and all losses, damages, rights, claims, and actions of any kind including, without limitation, personal injuries, death and property damage, that is either directly or indirectly related to or arises from (i) any interaction you have with other Users, or (ii) your participation in any of our offline events. If you are a California resident, you hereby waive California Civil Code Section 1542, which states:  A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor. 
</p><p>
16. INDEMNITY. You agree to defend, indemnify and hold Clofus, its officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with your access to or use of the Content or Services or your violation of these Terms of Service.
</p><p>
17. RESPONSIBILITY. Your interaction with other Users on the Services or with advertisers or other third parties, including any payment or delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and the other User, advertiser or third party. You agree that Clofus will not be responsible for any loss or damage incurred as the result of any such dealings or with respect to any third party s use or disclosure of your personal information that you make available to them. If there is a dispute between you and any third party (including any User), we are under no obligation to become involved and you agree not to involve us unless we request otherwise in writing; however, we reserve the right, but have no obligation, to monitor disputes between you and other Users.
</p><p>
18. THIRD PARTY SERVICES AND PARTNER COMMUNITIES. The Services may contain links to third party websites, applications and/or services ( Third Party Services ) (i) placed by us as a service to those interested in this information; or (ii) posted by other Users. We may also place links or enable interoperability to Partner Communities or use other means that allow you to connect the Clofus Services to Partner Communities to give you more possibilities. You use all such links to Third Party Services and Partner Communities at your own risk. To the extent such links are provided by us, they are provided only as a convenience and such links to Third Party Services or Partner Communities do not imply our endorsement, adoption or sponsorship of or affiliation with such Third Party Service or Partner Community. We accept no responsibility for reviewing changes or updates to or the quality, content, policies, nature or reliability of Third Party Services or Partner Communities or links from those third parties back to the Services. You should review applicable terms and policies, including privacy and data gathering practices, for any Third Party Services or Partner Communities and should make whatever investigation you feel necessary or appropriate and choose appropriate settings for sharing your personal information before proceeding with any interaction with a Third Party Service or Partner Community.
</p><p>
19. COMMENTS. If you have comments on the Clofus Services or ideas on how we might improve, please contact us here. You acknowledge and agree that if you submit any comments or ideas to us, you hereby grant to us a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, sub-licensable and transferable license under any and all intellectual property rights that you own or control to use, copy, modify, create derivative works based upon and otherwise exploit the comments and ideas for any purpose. The licenses granted under this Section shall survive the termination or expiration of these Terms of Service.
</p><p>
20. INITIAL RESOLUTION OF QUESTIONS OR DISPUTES. If you have any questions or concerns about the Services or these Terms of Services, we strongly encourage you to first contact us directly by going to the  Contact Us  page located here.
</p><p>
21. ARBITRATION. For any claim (excluding claims for injunctive or other equitable relief) where the total amount of the award sought is less than $10,000, either party may elect to resolve the dispute in a cost effective manner through binding non-appearance-based arbitration. In the event a party elects arbitration, they shall initiate such arbitration through an established alternative dispute resolution ( ADR ) provider mutually agreed upon by the parties. The ADR provider and the parties must comply with the following rules: (i) the arbitration shall be conducted by telephone, online and/or be solely based on written submissions, the specific manner shall be chosen by the party initiating the arbitration; (ii) the arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties; and (iii) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Any dispute resolution proceedings, whether in arbitration or court, will be conducted only on an individual basis and not in a class or representative action or as a named or unnamed member in a class, consolidated, representative or private attorney general legal action.
</p><p>
22. LAW AND JURISDICTION. These Terms of Service shall be governed in all respects by the laws of the State of California without giving effect to any conflicts of laws principles that require the application of the law of a different jurisdiction. You agree that any claim or dispute you may have against Clofus must be resolved by a court located in San Francisco County, California, except as otherwise agreed by the parties or as in the arbitration option. You agree to submit to the personal jurisdiction of the courts located within San Francisco County, California for the purpose of litigating all such claims or disputes.
</p><p>
23. MISCELLANEOUS PROVISIONS. If for any reason a court of competent jurisdiction finds any provision or portion of this Terms of Service to be unenforceable, the remainder of the Terms of Service will continue in full force and effect. The provisions of these Terms of Service that by their nature are continuing will survive any termination. This Terms of Service constitutes the entire agreement between the parties with respect to the subject matter and supersedes and replaces all prior or contemporaneous communications or agreements, written or oral. Any waiver of any provision of these Terms of Service will be effective only if in writing and signed by Clofus.
</p><p>
Effective Date: August 16, 2012
			
			</div>
		
		</div>
		<div class="footer">
			<div class="footer1">Copyright 2012 Clofus. All rights reserved.</div>
			<div class="footer2"><a href="terms.php">Terms & Conditions</a>&nbsp;|&nbsp;<a href="terms.php">Privacy Policy</a></div>
		</div>	

	</div>
</div>


</div>
</html>